### ISSUE TITLE
Missing authorship - Tidabius vector

### ISSUE THREAD

**Issue by ManonGros** [Archilegt/Myriatrix#4]
Hi Carlos,

I am going over some feedback we got about the GBIF Backbone taxonomy. [This issue](https://github.com/gbif/backbone-feedback/issues/22) (amongst other things) made me notice that Tidabius vector (https://www.gbif.org/species/10377621) was missing the authorship information. This generated the creation of a duplicate record in the GBIF Backbone taxonomy as this other record has authorship https://www.gbif.org/species/10618694.
Would it be possible to add the authorship to this record in Myriatrix? This will allow our system to not avoid generating duplicate in the next backbone update.
Thanks!

**Comment by ManonGros** [comment]
It looks to also be the case for https://www.gbif.org/species/11809079 (Cryptops (Cryptops) vector)

**Comment by Archilegt** [comment]
Hi Marie,
Thank you for your email.

Chamberlin (1931) added to the biblio database and tagged with four names:
https://myriatrix.myspecies.info/content/three-new-chilopods
The four names updated with authorship and further data.

All Scrathpads will be frozen on July 14th and the underlying Drupal
scrapped off. We may want to trigger one last DwC export before that. I was
planning to update phylum Onychophora the upcoming weekend.

Apologies for the shortness. Too many things, too little time.

Cheers,
C

**Comment by Archilegt** [comment]
Closed as completed.

**Comment by ManonGros** [comment]
Thank you Carlos! Much appreciated
